version: "3"
services:
  console:
    image: styletang/rocketmq-console-ng
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - namesrv
    ports:
      - "17880:8080"
    networks:
      - rocketmq
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  namesrv:
    image: rocketmqinc/rocketmq-namesrv:4.5.0-alpine
    ports:
      - "9876:9876"
    networks:
      - rocketmq
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  broker:
    image: rocketmqinc/rocketmq-broker:4.5.0-alpine
    environment:
      NAMESRV_ADDR: "namesrv:9876"
      BROKER_ID: "0"
      #JAVA_OPT_EXT: "-server -Xms128m -Xmx512m -Xmn128m"
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    networks:
      - rocketmq
    volumes:
      - $PWD/data/logs:/root/rocketmq-4.5.0/logs
      - $PWD/data/store:/root/rocketmq-4.5.0/store
     # - $PWD/data/broker.conf:/root/rocketmq-4.5.0/conf/broker.conf
   # entrypoint: bash -c "chmod -R 777 /etc/rocketmq" 
    depends_on:
      - namesrv
    deploy:
      replicas: 1
      restart_policy:
        condition: any
networks:
  rocketmq:
#    name: rocketmq
#    #    driver: bridge
